deadlines:
  - name: "ASQ - Richard A. Freund (example)"
    date: "2026-04-01"
  - name: "Studyportals (example)"
    date: "2026-05-31"
  - name: "GSoC contributors application window (official)"
    date: "2026-03-31"
